"""Tests for arm routing — the assertion that catches an excellent-looking result.

If a LoRA arm generates for a poem it trained on, every grounding number rises
and nothing errors. The outputs look fine, the run completes, the figures are
plausible. This is the only place that failure is detectable, which is why the
check re-derives the expected adapter independently rather than trusting what
generation recorded.

Under 5-fold the risk was a per-poem lookup: `lora_r8` had five adapters and
each could legitimately generate only for the poems its own fold held out. The
holdout design removes the lookup — one adapter per arm, and the test poems were
held out by every model — so the surviving risk is a poem from the POOL reaching
generation. These tests pin both halves.
"""

from __future__ import annotations

import config
from src.generate import inference


TEST_IDS = {1, 2, 3, 4, 5, 6}
POOL_ID = 99


def output(poem_id, arm, adapter=...):
    if adapter is ...:
        adapter = inference.adapter_for(arm)
        adapter = str(adapter) if adapter else None
    return {"poem_id": poem_id, "arm": arm, "adapter": adapter,
            "interpretation": "text"}


# --- routing ------------------------------------------------------------------

def test_each_arm_routes_to_its_own_adapter():
    """Ends-with rather than equals: SMOKE prefixes the directory so a
    five-step gpt2 adapter cannot occupy a real adapter's path. The convention
    that matters — the rank in the name — is what is pinned here."""
    for rank in config.LORA_ARM_RANKS:
        assert inference.adapter_for(f"lora_r{rank}").name.endswith(
            f"lora_r{rank}")


def test_routing_needs_no_fold_lookup():
    """The lookup WAS the hazard. It is gone, and a signature that still took a
    poem id would invite it back."""
    import inspect

    assert list(inspect.signature(inference.adapter_for).parameters) == ["arm"]


def test_untrained_arms_have_no_adapter():
    for arm in inference.UNTRAINED_ARMS:
        assert inference.adapter_for(arm) is None


def test_the_two_lora_arms_have_distinct_adapters():
    """Sharing a path would silently overwrite one with the other, and the
    r8-vs-r16 contrast would compare a model against itself."""
    paths = {inference.adapter_for(f"lora_r{r}")
             for r in config.LORA_ARM_RANKS}
    assert len(paths) == len(config.LORA_ARM_RANKS)


def test_an_unknown_arm_raises():
    """Rather than returning None, which would silently generate the arm from
    the base model and label the output as fine-tuned."""
    try:
        inference.adapter_for("lora_r32")
    except ValueError as error:
        assert "unknown arm" in str(error)
        return
    raise AssertionError("an arm with no adapter was routed anyway")


# --- the audit ----------------------------------------------------------------

def test_correct_routing_passes():
    inference.assert_routing(
        [output(p, "lora_r8") for p in TEST_IDS] +
        [output(1, "base_few", adapter=None)], TEST_IDS)


def test_a_poem_outside_the_test_partition_is_caught():
    """THE failure, under this design. Every LoRA arm trained on the pool, so an
    output for a pool poem was produced by a model that had already read it."""
    outputs = [output(p, "lora_r8") for p in TEST_IDS]
    outputs.append(output(POOL_ID, "lora_r8"))
    try:
        inference.assert_routing(outputs, TEST_IDS)
    except AssertionError as error:
        assert "outside the test partition" in str(error)
        return
    raise AssertionError("a poem the model trained on passed the audit")


def test_generation_refuses_a_pool_poem_before_spending_a_gpu_hour():
    """Checked up front, not after the fact: the cost of finding out afterwards
    is a whole session, and good scores do not look like a failure."""
    poems = [{"poem_id": POOL_ID, "title": "T", "author": "A",
              "lines": ["a"], "interpretation": "x"}]
    try:
        inference.generate_arm(poems, "lora_r8", lambda _: None,
                               test_ids=TEST_IDS)
    except AssertionError as error:
        assert "not in the test partition" in str(error)
        return
    raise AssertionError("generation started on a poem the model trained on")


def test_an_arm_generated_by_the_wrong_adapter_is_caught():
    """Not a leak under this design — every adapter held out every test poem —
    but it relabels one arm as another, which is enough to make lora_r8 vs
    lora_r16 a comparison of a model against itself."""
    bad = output(1, "lora_r8", adapter=str(inference.adapter_for("lora_r16")))
    try:
        inference.assert_routing([bad], TEST_IDS)
    except AssertionError as error:
        assert "records adapter" in str(error)
        return
    raise AssertionError("an arm generated by another arm's adapter passed")


def test_untrained_arm_carrying_an_adapter_is_caught():
    bad = output(1, "base_zero", adapter="some/adapter")
    try:
        inference.assert_routing([bad], TEST_IDS)
    except AssertionError:
        return
    raise AssertionError("an untrained arm with an adapter passed")


# --- prompts ------------------------------------------------------------------

def poem(pid=1):
    return {"poem_id": pid, "title": "T", "author": "A", "linecount": 2,
            "lines": ["a line", "another line"], "interpretation": "an example"}


def test_base_zero_and_lora_share_a_prompt():
    """The weights must be the only difference between them, or the comparison
    measures prompting as well."""
    assert (inference.build_prompt(poem(), "base_zero")
            == inference.build_prompt(poem(), "lora_r8"))


def test_base_few_prepends_examples():
    few = inference.build_prompt(poem(), "base_few", exemplars=[poem(2)])
    assert len(few) > len(inference.build_prompt(poem(), "base_zero"))
    assert "an example" in few


def test_base_few_without_exemplars_raises():
    """Silently falling back would make base_few identical to base_zero, and the
    in-context contribution would read as zero."""
    try:
        inference.build_prompt(poem(), "base_few", exemplars=[])
    except AssertionError:
        return
    raise AssertionError("base_few built a prompt with no exemplars")


# --- the adapter a run writes is the one generation looks for -----------------

def test_training_and_generation_agree_on_the_adapter_path():
    """The convention was written in three places and two spellings, agreeing
    only while LORA_RANK == 8. A mismatch does not fail cleanly for every poem
    — it loses one arm, which reads as a partial run rather than a naming bug.

    Three spellings have to meet: what `final_specs` names the run, where
    `run_adapter_dir` writes it, and where `adapter_for` looks for it."""
    from src.train import sweep

    for spec in sweep.final_specs({"learning_rate": 2e-4}):
        assert (config.run_adapter_dir(spec["run"])
                == config.adapter_dir(spec["rank"])
                == inference.adapter_for(spec["run"]))


def test_the_arms_and_their_ranks_cannot_drift_apart():
    """config.ARMS names what is generated and LORA_ARM_RANKS names what is
    trained. If they disagree, one arm generates from the base model with
    nothing raising."""
    for rank in config.LORA_ARM_RANKS:
        assert f"lora_r{rank}" in config.ARMS
    assert len(config.ARMS) == len(inference.UNTRAINED_ARMS) + \
        len(config.LORA_ARM_RANKS)


def test_train_saves_the_adapter_in_the_same_call():
    """Kaggle sessions die. An adapter saved by a LATER notebook cell is one a
    dead kernel loses, costing the run rather than the cell."""
    import inspect

    from src.train import loop

    source = inspect.getsource(loop.train)
    assert "save_adapter" in source
    assert "run_adapter_dir" in source


# --- generation must never truncate a prompt ----------------------------------

def test_generation_context_exceeds_the_training_cap():
    """MAX_SEQ_LEN is a TRAINING memory limit — attention is quadratic and at an
    effective batch of 16 a T4 cannot hold more. Generation is batch 1 under
    no_grad, so it does not apply, and the model itself handles 32,768.

    Reusing the training cap capped base_few's prompts at 1,648 tokens when they
    run to 3,641.
    """
    assert config.GEN_MAX_CONTEXT > config.MAX_SEQ_LEN


def test_no_evaluation_prompt_is_truncated():
    """The bug this guards: every base_few prompt overran the old cap and was
    cut from the RIGHT, keeping the three exemplars and discarding the poem
    being interpreted. base_few would have scored near zero on grounding, and
    base_few vs lora_r8 — the headline contrast — would have measured
    truncation.
    """
    from src.data import filter as F
    from src.data import splits
    from src.generate import inference

    pairs = splits.load_training_pairs()
    if not pairs or not config.HOLDOUT_PATH.exists():
        return

    holdout = splits.load_holdout()
    by_id = {p["poem_id"]: p for p in pairs}
    exemplars = [by_id[i] for i in holdout["exemplars"] if i in by_id]
    evaluation = [by_id[i] for i in holdout["test"] if i in by_id]
    tokenizer = F.get_tokenizer()

    budget = config.GEN_MAX_CONTEXT - config.GEN_MAX_NEW_TOKENS
    for arm in ("base_zero", "base_few", "lora_r8"):
        longest = max(
            len(tokenizer(inference.build_prompt(p, arm, exemplars))["input_ids"])
            for p in evaluation)
        assert longest <= budget, (
            f"{arm}'s longest prompt is {longest} tokens against a {budget} "
            f"budget; it would be truncated and the target poem lost")


def test_generate_one_asserts_rather_than_truncating():
    import inspect

    from src.generate import inference

    source = inspect.getsource(inference.generate_one)
    assert "truncation=True" not in source
    assert "GEN_MAX_CONTEXT" in source


def test_every_arm_shares_one_context_limit():
    """A per-arm context limit would be a per-arm handicap, and the comparison
    would measure the limit rather than the adaptation method."""
    import inspect

    from src.generate import inference

    source = inspect.getsource(inference.generate_one)
    assert source.count("GEN_MAX_CONTEXT") >= 1
    assert "arm" not in source.split("assert")[1][:400]


# --- the model loader ---------------------------------------------------------

def test_untrained_arms_share_one_base_model():
    """They differ only in the prompt, so reloading between them buys nothing."""
    load = inference.model_loader(base="BASE")
    assert load(None) is load(None) is "BASE"


def test_each_adapter_gets_a_fresh_base(monkeypatch):
    """PeftModel.from_pretrained WRAPS the module it is handed. Reusing one base
    across two adapters leaves the second arm generating from both — no error,
    fluent output, and lora_r16 silently becomes a blend nobody trained."""
    from src.model import setup

    handed = []

    def fake_load_adapter(path, base=None):
        handed.append(base)
        return f"model@{path}"

    monkeypatch.setattr(setup, "load_adapter", fake_load_adapter)

    load = inference.model_loader(base="BASE")
    first = load(inference.adapter_for("lora_r8"))
    second = load(inference.adapter_for("lora_r16"))

    assert first != second
    assert handed == [None, None], (
        "an adapter was stacked onto a model that already had one")


# --- ablation arms: model-free metrics only -----------------------------------

def test_ablation_arms_are_not_in_ARMS():
    """ARMS is what every judge and hypothesis path iterates. An ablation arm
    reaching it would put an unregistered arm into H1-H3 and spend judge budget
    on 3 x 152 x 3 x 2 pairs nobody planned for."""
    assert not (set(config.ABLATION_ARMS) & set(config.ARMS))


def test_ablation_arms_track_the_data_size_sweep():
    """Derived, not written out, so they cannot drift from the runs
    sweep.ablation_specs actually produces."""
    from src.train import sweep

    produced = {s["run"] for s in sweep.ablation_specs(
        {"rank": 8, "learning_rate": 2e-4})}
    assert set(config.ABLATION_ARMS) == produced


def test_each_ablation_arm_routes_to_its_own_adapter():
    for arm in config.ABLATION_ARMS:
        assert inference.adapter_for(arm).name.endswith(arm)


def test_an_unknown_ablation_arm_still_raises():
    """The guard that keeps a typo from silently generating an arm from the
    base model and labelling the output as fine-tuned."""
    try:
        inference.adapter_for("ablation_n999")
    except ValueError as error:
        assert "unknown arm" in str(error)
        return
    raise AssertionError("an arm with no adapter was routed anyway")


def test_no_two_arms_share_an_adapter():
    """Across every arm that has one — a shared path would silently relabel one
    arm as another, and the data-size curve would join duplicate points."""
    paths = [inference.adapter_for(a)
             for a in config.ARMS + config.ABLATION_ARMS
             if a not in inference.UNTRAINED_ARMS]
    assert len(set(paths)) == len(paths)
