"""Tests for fold routing — the assertion that catches an excellent-looking result.

If `lora_r8` generates a poem using an adapter that trained on it, every
grounding number rises and nothing errors. The outputs look fine, the run
completes, the figures are plausible. This is the only place that failure is
detectable, which is why the check re-derives the mapping independently rather
than trusting what generation recorded.
"""

from __future__ import annotations

import config
from src.generate import inference


FOLD_OF = {1: 0, 2: 0, 3: 1, 4: 2, 5: 3, 6: 4}


def output(poem_id, arm, adapter=..., fold=...):
    if adapter is ...:
        adapter = inference.adapter_for(poem_id, arm, FOLD_OF)
        adapter = str(adapter) if adapter else None
    return {"poem_id": poem_id, "arm": arm, "adapter": adapter,
            "fold_id": FOLD_OF[poem_id] if fold is ... else fold,
            "interpretation": "text"}


# --- routing ------------------------------------------------------------------

def test_each_poem_routes_to_its_own_folds_adapter():
    for poem_id, fold in FOLD_OF.items():
        path = inference.adapter_for(poem_id, "lora_r8", FOLD_OF)
        assert path.name == f"lora_r8_fold{fold}"


def test_untrained_arms_have_no_adapter():
    for arm in ("template", "base_zero", "base_few"):
        assert inference.adapter_for(1, arm, FOLD_OF) is None


def test_a_poem_with_no_fold_cannot_be_routed():
    try:
        inference.adapter_for(999, "lora_r8", FOLD_OF)
    except AssertionError:
        return
    raise AssertionError("a poem outside the fold assignment was routed anyway")


def test_lora_r16_refuses_poems_it_trained_on():
    """It is trained on one fold's partition, so every OTHER fold's poems were
    in its training data. Generating for them evaluates on training data."""
    other = next(p for p, f in FOLD_OF.items() if f != config.SINGLE_SPLIT_FOLD)
    try:
        inference.adapter_for(other, "lora_r16", FOLD_OF)
    except AssertionError as error:
        assert "TRAINING data" in str(error)
        return
    raise AssertionError("lora_r16 was routed a poem it trained on")


def test_lora_r16_accepts_its_own_folds_poems():
    own = next(p for p, f in FOLD_OF.items() if f == config.SINGLE_SPLIT_FOLD)
    assert inference.adapter_for(own, "lora_r16", FOLD_OF) is not None


# --- the audit ----------------------------------------------------------------

def test_correct_routing_passes():
    inference.assert_fold_routing(
        [output(p, "lora_r8") for p in FOLD_OF] +
        [output(1, "base_few", adapter=None)], FOLD_OF)


def test_wrong_adapter_is_caught():
    """The failure this module exists to prevent: poem 3 is held out by fold 1,
    so fold 0's adapter TRAINED on it."""
    bad = output(3, "lora_r8", adapter=str(config.ADAPTERS_DIR / "lora_r8_fold0"))
    try:
        inference.assert_fold_routing([bad], FOLD_OF)
    except AssertionError as error:
        assert "TRAINING data" in str(error)
        return
    raise AssertionError("a poem generated by a model that trained on it passed")


def test_one_adapter_for_everything_is_caught():
    """The specific mistake: load one adapter, generate all 150."""
    single = str(config.ADAPTERS_DIR / "lora_r8_fold0")
    outputs = [output(p, "lora_r8", adapter=single) for p in FOLD_OF]
    try:
        inference.assert_fold_routing(outputs, FOLD_OF)
    except AssertionError:
        return
    raise AssertionError("a single-adapter run passed the routing audit")


def test_recorded_fold_must_match_the_assignment():
    try:
        inference.assert_fold_routing([output(3, "lora_r8", fold=0)], FOLD_OF)
    except AssertionError:
        return
    raise AssertionError("a mislabelled fold_id passed")


def test_untrained_arm_carrying_an_adapter_is_caught():
    bad = output(1, "base_zero", adapter="some/adapter")
    try:
        inference.assert_fold_routing([bad], FOLD_OF)
    except AssertionError:
        return
    raise AssertionError("an untrained arm with an adapter passed")


# --- prompts ------------------------------------------------------------------

def poem(pid=1):
    return {"poem_id": pid, "title": "T", "author": "A", "linecount": 2,
            "lines": ["a line", "another line"], "interpretation": "an example"}


def test_base_zero_and_lora_share_a_prompt():
    """The weights must be the only difference between them, or the comparison
    measures prompting as well."""
    assert (inference.build_prompt(poem(), "base_zero")
            == inference.build_prompt(poem(), "lora_r8"))


def test_base_few_prepends_examples():
    few = inference.build_prompt(poem(), "base_few", exemplars=[poem(2)])
    assert len(few) > len(inference.build_prompt(poem(), "base_zero"))
    assert "an example" in few


def test_base_few_without_exemplars_raises():
    """Silently falling back would make base_few identical to base_zero, and the
    in-context contribution would read as zero."""
    try:
        inference.build_prompt(poem(), "base_few", exemplars=[])
    except AssertionError:
        return
    raise AssertionError("base_few built a prompt with no exemplars")
