"""Generate interpretations for all five arms on the evaluation poems.

**The fold routing in this module is the single easiest way to invalidate the
whole project.** For ``lora_r8`` each poem must be generated by the adapter of
the fold that held *that poem* out. Loading one adapter and generating all 150
silently evaluates 120 of them on training data, inflates every grounding
number, and raises nothing — the outputs look fine, the run completes, and the
result is excellent for the wrong reason.

So the adapter is looked up per poem and never taken as a global, and
:func:`assert_fold_routing` re-derives the mapping from the fold assignment and
fails if any output disagrees.

**Decoding is fixed identically across every arm** — temperature, top-p,
repetition penalty, token budget, seed. Otherwise the comparison measures
sampling settings rather than adaptation method. All five arms run in one
session, which is what makes "identical" a fact rather than an intention.
"""

from __future__ import annotations

import json
import logging

import config

log = logging.getLogger(__name__)


def build_prompt(poem: dict, arm: str, exemplars: list[dict] | None = None) -> str:
    """The prompt for one poem under one arm.

    ``base_zero`` and every LoRA arm get the **same** prompt — the one the
    teacher was given and the model was trained on. That is deliberate: it makes
    the weights the only difference between them, so ``base_zero`` vs
    ``lora_r8`` isolates the weight update and nothing else.

    ``base_few`` prepends worked examples, which is the whole of what it adds.
    Its exemplars come from a pool excluded from every evaluation fold, so a
    poem can never appear both as a prompt example and as an evaluation item.
    """
    from src.train.dataset import build_prompt as training_prompt

    body = training_prompt(poem)
    if arm != "base_few":
        return body

    assert exemplars, "base_few needs exemplars; without them it IS base_zero"
    shown = "\n\n".join(
        f"{training_prompt(example)}{example['interpretation']}"
        for example in exemplars[:config.N_FEWSHOT]
    )
    return f"{shown}\n\n{body}"


def adapter_for(poem_id: int, arm: str, fold_of: dict) -> "object | None":
    """Which adapter must generate this poem, or None for an untrained arm.

    The function this module exists to get right. ``lora_r8`` has one adapter
    per fold and the correct one is decided by which fold held this poem out —
    never by which adapter happens to be loaded.

    ``lora_r16`` is trained on a single fold's partition, so it can only
    legitimately generate for poems that fold held out. Asking it for any other
    poem is a request to evaluate on training data, and it raises rather than
    returning something plausible.
    """
    if arm in ("template", "base_zero", "base_few"):
        return None

    fold = fold_of.get(poem_id)
    assert fold is not None, (
        f"poem {poem_id} has no fold; it cannot be routed to an adapter and "
        f"must not be generated for a trained arm")

    # Via config.adapter_dir, never spelled out here: training writes the same
    # path, and two spellings of one convention drift into a missing adapter for
    # one arm or one fold — which reads as a partial run, not as a naming bug.
    if arm == "lora_r8":
        return config.adapter_dir(8, fold)

    if arm == "lora_r16":
        assert fold == config.SINGLE_SPLIT_FOLD, (
            f"lora_r16 is trained only on fold {config.SINGLE_SPLIT_FOLD}'s "
            f"partition, so poem {poem_id} (fold {fold}) was in its TRAINING "
            f"data. Generating for it would evaluate on training data.")
        return config.adapter_dir(16, fold)

    raise ValueError(f"unknown arm {arm!r}")


def generate_one(prompt: str, model, tokenizer) -> str:
    """One interpretation, with the fixed decoding settings.

    Every parameter comes from config and none is passed per-arm, because a
    per-arm override is exactly how a comparison quietly becomes a comparison of
    sampling settings.
    """
    import torch

    encoded = tokenizer(prompt, return_tensors="pt",
                        truncation=True,
                        max_length=config.MAX_SEQ_LEN - config.GEN_MAX_NEW_TOKENS
                        ).to(model.device)
    torch.manual_seed(config.SEED)

    with torch.no_grad():
        output = model.generate(
            **encoded,
            max_new_tokens=config.GEN_MAX_NEW_TOKENS,
            do_sample=True,
            temperature=config.GEN_TEMPERATURE,
            top_p=config.GEN_TOP_P,
            repetition_penalty=config.GEN_REPETITION_PENALTY,
            pad_token_id=tokenizer.pad_token_id,
        )
    new = output[0][encoded["input_ids"].shape[1]:]
    return tokenizer.decode(new, skip_special_tokens=True).strip()


def _key(record) -> tuple:
    return (record["poem_id"], record["arm"]) if isinstance(record, dict) else record


def load_cached() -> list[dict]:
    """Arm outputs already generated, newest per (poem, arm) winning."""
    path = config.ARM_OUTPUTS_PATH
    if not path.exists():
        return []
    by_key: dict = {}
    for line in path.open(encoding="utf-8"):
        if line.strip():
            record = json.loads(line)
            by_key[_key(record)] = record
    return list(by_key.values())


def _append(record: dict) -> None:
    config.ARM_OUTPUTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with config.ARM_OUTPUTS_PATH.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, ensure_ascii=False) + "\n")


def generate_arm(poems: list[dict], arm: str, fold_of: dict,
                 load_model, tokenizer=None,
                 exemplars: list[dict] | None = None) -> list[dict]:
    """Generate one arm for every poem, routing each to its own adapter.

    Args:
        load_model: called with an adapter path (or None) and returns a model.
            Passed in rather than imported so the caller controls loading and
            can cache — ``lora_r8`` needs five adapters across 150 poems, and
            reloading per poem would dominate the runtime.

    ``template`` needs no model at all but is generated in this same pass
    anyway, so every arm lands in one file written by one code path.
    """
    done = {_key(r) for r in load_cached()}
    pending = [p for p in poems if (p["poem_id"], arm) not in done]
    log.info("%s: %d cached, %d to generate", arm, len(poems) - len(pending),
             len(pending))
    if not pending:
        return [r for r in load_cached() if r["arm"] == arm]

    # Grouped by adapter so each is loaded once, not once per poem.
    grouped: dict = {}
    for poem in pending:
        grouped.setdefault(adapter_for(poem["poem_id"], arm, fold_of),
                           []).append(poem)

    for adapter, group in grouped.items():
        model = None if arm == "template" else load_model(adapter)
        for poem in group:
            text = (config.TEMPLATE_ARM_TEXT if arm == "template"
                    else generate_one(build_prompt(poem, arm, exemplars),
                                      model, tokenizer))
            _append({
                "poem_id": poem["poem_id"],
                "arm": arm,
                # Recorded so the routing can be audited after the fact, not
                # merely trusted at generation time.
                "fold_id": fold_of.get(poem["poem_id"]),
                "adapter": str(adapter) if adapter else None,
                "interpretation": text,
            })

    return [r for r in load_cached() if r["arm"] == arm]


def assert_fold_routing(outputs: list[dict], fold_of: dict) -> None:
    """Every trained-arm output came from the adapter of its own held-out fold.

    Re-derives the mapping independently rather than trusting what generation
    recorded. This is the assertion that catches the failure which otherwise
    looks like an excellent result: a model evaluated on its own training data
    scores higher on every metric, and nothing else in the pipeline would
    notice.
    """
    for record in outputs:
        arm = record["arm"]
        if arm in ("template", "base_zero", "base_few"):
            assert record["adapter"] is None, (
                f"{arm} is untrained but recorded adapter {record['adapter']}")
            continue

        expected = str(adapter_for(record["poem_id"], arm, fold_of))
        assert record["adapter"] == expected, (
            f"poem {record['poem_id']} ({arm}) was generated by "
            f"{record['adapter']} but is held out by fold "
            f"{fold_of.get(record['poem_id'])}, whose adapter is {expected}. "
            f"This poem was in that model's TRAINING data.")
        assert record["fold_id"] == fold_of.get(record["poem_id"]), (
            f"poem {record['poem_id']} records fold {record['fold_id']} but the "
            f"assignment says {fold_of.get(record['poem_id'])}")

    log.info("fold routing verified for %d outputs", len(outputs))


def coverage(outputs: list[dict], poems: list[dict]) -> dict:
    """How many poems each arm produced, so a partial run is visible."""
    counts: dict = {}
    for record in outputs:
        counts[record["arm"]] = counts.get(record["arm"], 0) + 1
    return {arm: f"{counts.get(arm, 0)}/{len(poems)}" for arm in config.ARMS}


def _smoke() -> None:
    """All five arms on a handful of poems, on CPU, in under a minute.

    The fold routing is the assertion this exists to exercise. It is the single
    easiest way to invalidate the project — an adapter that generated for a poem
    it was trained on inflates every metric and raises nothing — so it is
    checked here rather than discovered on Kaggle.
    """
    from src.data import splits
    from src.model import setup

    config.configure_logging()
    assert config.SMOKE, "run with SMOKE=1; this is a size flag, not a mode"

    # Start clean, or a second invocation reports "0 to generate" and exercises
    # the cache instead of the generation path it exists to test. Safe because
    # SMOKE resolves this to smoke_arm_outputs.json.
    assert "smoke" in config.ARM_OUTPUTS_PATH.name, "refusing to clear real outputs"
    config.ARM_OUTPUTS_PATH.unlink(missing_ok=True)

    pairs = splits.load_training_pairs()
    fold_of = splits.load_assignment()
    assert pairs and fold_of, "training pairs or fold assignment missing"

    evaluation = splits.load_evaluation_folds()
    poems = [p for p in pairs if p["poem_id"] in evaluation][:3]
    assert poems, "no evaluation poems found in the pairs file"
    exemplars = pairs[:config.N_FEWSHOT]

    tokenizer = setup.load_tokenizer()
    base = setup.load_base_model()
    # One model for every arm here: the smoke run checks routing and plumbing,
    # not adapter quality, and no adapters exist before the first Kaggle run.
    for arm in ("template", "base_zero", "base_few"):
        generate_arm(poems, arm, fold_of, lambda _: base, tokenizer, exemplars)

    outputs = [r for r in load_cached()
               if r["poem_id"] in {p["poem_id"] for p in poems}]
    assert_fold_routing(outputs, fold_of)

    print(f"\n  coverage {coverage(outputs, poems)}")
    for arm in ("template", "base_zero", "base_few"):
        text = next(r["interpretation"] for r in outputs if r["arm"] == arm)
        print(f"\n  {arm}: {text[:110]!r}")
    print(f"\n  fold routing verified; adapters for the LoRA arms are checked "
          f"by tests/test_fold_routing.py")


if __name__ == "__main__":
    _smoke()
